apiVersion: v1
kind: Service
metadata:
  name: webapp-service-v2
  namespace : webapp
  labels:
    app: employees
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: employees
    version : v2