apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v2
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - image: 610510370017.dkr.ecr.us-east-1.amazonaws.com/webapp:v2.0
        name: webapp-container
        ports:
        - containerPort: 8080
        env:
        - name: DBPWD
          value: pw
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"